sonar.projectKey=zept888_go-project-244
sonar.organization=zept888
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out